language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=1.11.24

script:
  - coverage run --source='.' manage.py test --setting=todolistsite.settings.testing

install:
  - pip install -r requirements.txt

after_success:
  - coveralls