# Generated by Django 2.2.4 on 2019-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20190828_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.CharField(default='', max_length=40),
        ),
    ]
